### PR TITLE
Refactor, improve and tidy some of the plugin code

### LINKED ISSUE #56: Renaming `dismiss` to `stopVuforia`
​
## Expected Behavior
If the user calls `startVuforia(...);` to begin a Vuforia session, should they call `stopVuforia();` to end it?
​
## Current Behavior
The user current has to call `startVuforia(...);` to begin and `dismiss();` to end it.
​
## Possible Solution
Rename `dismiss` to `stopVuforia`.
​
## Context
This just seems a little strange and inconsistent. It would be nice if the method names were consistent.

### LINKED ISSUE #59: dismiss() method doesn't provide any user feedback
​
## Expected Behavior
When you call `dismiss(...)`, you should be able to include a callback that gets called when it successfully happens (or if it doesn't happen).
​
## Current Behavior
When you call `dismiss(...)​`, nothing happens (as far as Cordova is concerned). Which, wouldn't be a problem if we could assume it always works. However, there is a situation where a `dismiss()` call will do nothing.

If you create a call such as this: 
```javascript
setTimeout(function(){ 
  navigator.VuforiaPlugin.dismiss();
  CordovaApp.showOutOfTimeModal();
}, 4000);
```

Your application will wait 4 seconds and close the Vuforia session. Now, if the user does not have a session open (either because they closed it themselves, or they found an image), the Cordova app will still call `CordovaApp.showOutOfTimeModal();`. Imagine a scenario where the user has found an image within 4 seconds, and still gets shown a 'Out of time' modal. This is not ideal.

## Possible Solution
`dismiss()` should take a callback which will get called when we are about to stop the Vuforia session.

The callback should receive a data object saying wether the session was or was not closed. For example, if you call `dismiss()` when there is no session it would look something like:

```json
{
  "success": false,
  "message": "No Vuforia session running"
}
```

If there is a session running, you would get something like:

```json
{
  "success": true
}
```

Then your call to dismiss would look more like this:

```javascript
setTimeout(function(){ 
  navigator.VuforiaPlugin.dismiss(function(data){
    var data = JSON.parse(data);
    
   console.log("dismiss returned: ", data.success, " and message: ", data.message);

    if(data.success){
      CordovaApp.showOutOfTimeModal();
    }
  });
}, 4000);
```

## Context
Not having a callback kind of neuters the application flow when it comes to dismissing. If you cant tell it actually did something, then you can't handle your application properly.

### PR DESCRIPTION
**Pull request by mattrayner**
## Description
Some of the plugin has got a little long in the tooth. Its had a lot of changes in the last few weeks, I'd like to do a first-pass tidy up to try and make it all nice and shiny again. 

## Motivation and Context
There's a few 'glaring' issues, by which I mean some things that aren't consistent with the rest of the plugin (Vuforia libraries in the wrong place for example). These are just a few small improvements to help bring it back in line.

### Addresses:
1. Fixes #56
1. Fixes #59

## How Has This Been Tested?
Tested locally with an iOS 9 & iOS 10 device along with a Nexus 5 Android device.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by dsgriffin** [comment]
Is this one ready to be merged?

**Comment by mattrayner** [comment]
Not just yet - I was premature removing the QIP note :P

Think I should squash it too?

**Comment by dsgriffin** [comment]
Could do in places where it makes sense - otherwise this'll be ready to merge and a 2.1 release?

**Comment by mattrayner** [comment]
You know what, lets just get this merged in - the commits each do something unique and it doesnt seem right squashing it down.

**Pull request merged**
