### PR TITLE
Added the overlay hiding if the overlayMessage is null.

### PR DESCRIPTION
**Pull request by Stending**
The overlay text isn't always useful for us, so I just hide it if you send null for the overlayText param.
It works well on my side, and I didn't change many thing.
Tell me if you want me to comment it a bit more or to log more things.

### CODE REVIEW

**Comment by mattrayner** [comment]
@Stending - any chance you can rebase off of master? I'd like to get this merged in soon :+1:

**Comment by Stending** [comment]
Rebase done!

**Comment by mattrayner** [comment]
This is back out of sync 👎

If you rebase I will merge this in right away

**Comment by mattrayner** [comment]
Let me know if you get a chance to rebase this :D

**Comment by Stending** [comment]
Okay, finally, after the #60 PR, I think we don't need this one anymore.

**Comment by mattrayner** [comment]
Hi @Stending, that's great! However, we don't plan on going to 3.0.0 right away - if you could rebase this branch off master we could get it in right away

**Comment by Stending** [comment]
Okay, rebase done!

When do you plan to go to 3.0.0? All my next PR will be with the refactor options.

**Comment by mattrayner** [comment]
Hi @Stending, GitHub still says this is out of date?

**Comment by mattrayner** [comment]
Hopefully next week, we've got a few breaking changes in mind that we want to (ideally) release all at once.

**Comment by Stending** [comment]
Oh yeah sorry, it should be done now!

**Pull request merged**
