### PR TITLE
Implemented runtime Camera permissions check for Android 6

### LINKED ISSUE #29: Failed to initialise on Android 6
We are getting 'Failed to initialize Vuforia' on all devices running Android 6, latest cordova (but cordova.js is 5.1.1). The plugin works on devices running Android 5 and below. Have you had any success using this plugin with Android 6?

Edit: Manually allowing the camera permission in Android settings allows the plugin to work but obviously that is not ideal. Is there some way to force the plugin to ask the user for permission to use the camera on first run? I noticed that the cordova-camera plugin isn't a dependency of the plugin which I find a little odd. Adding the camera plugin manually has no effect.

I'm sure you're aware, but be advised of the security changes in Cordova 6 https://taco.visualstudio.com/en-us/docs/tutorial-cordova-5-readme/#changes-with-the-release-of-cordova-6

### PR DESCRIPTION
**Pull request by dsgriffin**
* Require Camera permissions on Vuforia start (required for Android 6, fixes #29)
* Handle error and display message mentioning required permission
* Bump version to 1.2.0

### CODE REVIEW

**Comment by remib** [comment]
There appears to be a missing semi-colon which is causing the build to fail at:

`import android.Manifest.permission`

**Comment by remib** [comment]
Also, the plugin is not working at all for me now on Android 4.4.2. In console I get:
`java.lang.NoSuchMethodError: android.app.Activity.requestPermissions`

**Comment by mattrayner** [comment]
Thanks for reporting this @remib - we're working on it right now

**Comment by remib** [comment]
Thanks guys

**Comment by remib** [comment]
It's worth noting that I added the semi colon myself, which led me to the second bug

**Comment by dsgriffin** [comment]
@remib Hey Remib, that was my fault (left out semi-colon and left in a line we didn't need 😢). Should work on Android 4/5/6 now.

**Comment by remib** [comment]
Cheers, all working now. Thanks again.

**Pull request merged**
