### PR TITLE
Update support for Vuforia to 5.5

### LINKED ISSUE #96: Update Vuforia support to 5.5
​
## Expected Behavior

The plugin should use Vuforia 5.5
​
## Current Behavior

The plugin uses 4.something
​
## Possible Solution

Implement 5.5 API support

## Context

In order to robustly support #88 (cloud recognition), we need to update to the most recent Vuforia API

### PR DESCRIPTION
**Pull request by mattrayner**
## Description

We're making changes to the plugin to support the Vuforia 5.5.9 APIs.

## Motivation and Context

We want to support cloud recognition [#88] and in order to do this using the latest codebase and documentation, we should update.

This will hopefully make the Vuforia section of our application more stable too!

Fixes #96 

## How Has This Been Tested?

iPhone 6S running iOS10 beta 3

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by mattrayner** [comment]
@dsgriffin ignore the failing dependency check - that's a BitHound issue, I'm in touch with support now trying to fix it

**Comment by mattrayner** [comment]
@dsgriffin can you check this on your Android device and report back?

I'm seeing an issue where opening one of the tests, then a second one causes the Vuforia app to break. My device is super old and I'm not sure if it's that, or an issue with the upgrade

**Comment by mattrayner** [comment]
I've discovered some issues with the Android code base - re-opening Vuforia i.e. scanning a target, recognising and then relaunching, is broken.

Working on a fix now

**Comment by dsgriffin** [comment]
@mattrayner Cool - actually trying to get my S4 Mini to turn on at the moment, might have to reset it or something as charging it isn't helping. 

Let me know when you've updated the fix and hopefully I'll have my phone working and we can merge.

**Comment by mattrayner** [comment]
@dsgriffin I've implemented a fix - the code's not particularly neat, but it works and we should re-factor after this update anyways - there's been a few API changes

**Comment by mattrayner** [comment]
@dsgriffin I have REVd the version number on this PR in preparation for release too :+1:

**Comment by dsgriffin** [comment]
@mattrayner `import com.qualcomm.vuforia.State;` in `ApplicationControl.java` needs to be changed to `import com.vuforia.State;` for it to work; not coming across any other issues though

**Comment by mattrayner** [comment]
@dsgriffin I've made that change for you :+1:

**Comment by dsgriffin** [comment]
Cool - looks good to merge then.

**Comment by mattrayner** [comment]
:+1: Do you think this should be a minor or bug fix? There's technically no API changes?

**Comment by mattrayner** [comment]
Cool, I previously REVd to 3.2.0 so I'll release it under that :smile:

**Pull request merged**
