### PR TITLE
Xcode settings automation

### PR DESCRIPTION
**Pull request by Stending**
Added a automation for the xcode settings, by using hooks.
It'll just change the header path and the AppDelegate.m file.

### CODE REVIEW

**Comment by mattrayner** [comment]
Hi Stending, this look amazing!
 The only feedback we'd have (other than this is awesome) is that, we'd like to support version 3 and 4 of cordova-ios - do you think it would be possible to get the cordova-ios version within your hooks and treat app-delegate appropriately for each?

@dsgriffin do you think that would be out of scope? We could always recommend the cordova-ios-3 branch if the hook doesn't work for people?

**Comment by dsgriffin** [comment]
First of all, cheers for the contribution @Stending!

A couple of things:

1. Would it be possible to rebase off `master` as there have been a lot of changes (e.g. Android 6 support ) recently.

2. When I try to run your code I get the following error (when testing on an iPhone 6s w/ Cordova 6):

> 2016-06-08 09:38:51.886 VuforiaPlugin[385:39488] ERROR: Plugin 'VuforiaPlugin' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
> 2016-06-08 09:38:51.886 VuforiaPlugin[385:39488] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["VuforiaPlugin1460823519","VuforiaPlugin","cordovaStartVuforia",["www\/targets\/StonesAndChips.xml",["stones","chips"],"Point your camera at a test image...","ASvJ+Kn\/\/\/\/\/

I also noticed that it doesn't generate the `#import <Cordova/CDVPlugin.h>` header in the `AppDelegate`.

That's it - let us know if there are any issues and thanks again, having this feature would be great!

**Comment by Stending** [comment]
I'll try to rebase off master, sorry if it doesn't work correctly!
I cannot promise it'll be today though, having a lot of work here!

For the #import <Cordova/CDVPlugin.h>, it wasn't use anywhere and I didn't
understand his utility, so I didn't re-add it in my file modification.
Especially because I was only modifying the method content, not the entire
file. It works well without it, though.

2016-06-08 10:46 GMT+02:00 daniel seán griffin <notifications@github.com>:

**Comment by Stending** [comment]
Okay, I rebased with the master, and fixed the bug where VuforiaPlugin wasn't found, that was a stupid mistake of mine.
Everything should work now, tell me if there is another problem!

**Comment by dsgriffin** [comment]
@Stending Works well 👍 this'll shorten the README a little 😆

**Pull request merged**
